# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

"""Utilities for managing paths in Spack.

TODO: this is really part of spack.config. Consolidate it.
"""
import os
import re
import getpass
import subprocess
import tempfile

import spack.paths


__all__ = [
    'substitute_config_variables',
    'substitute_path_variables',
    'canonicalize_path']

# Substitutions to perform
replacements = {
    'spack': spack.paths.prefix,
    'user': getpass.getuser(),
    'tempdir': tempfile.gettempdir(),
}

# This is intended to be longer than the part of the install path
# spack generates from the root path we give it.  Included in the
# estimate:
#
#   os-arch      ->   30
#   compiler     ->   30
#   package name ->   50   (longest is currently 47 characters)
#   version      ->   20
#   hash         ->   32
#   buffer       ->  138
#  ---------------------
#   total        ->  300
SPACK_MAX_INSTALL_PATH_LENGTH = 300
SPACK_PATH_PADDING_CHARS = 'spack_path_placeholder'
SPACK_PATH_PADDING_SIZE = len(SPACK_PATH_PADDING_CHARS)

try:
    path_max_proc  = subprocess.Popen(['getconf', 'PATH_MAX', '/'],
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.STDOUT)
    proc_output = str(path_max_proc.communicate()[0].decode())
    SPACK_SYS_MAX_PATH_LENGTH = int(proc_output)
except (ValueError, subprocess.CalledProcessError, OSError):
    # To be safe, if we couldn't determine the max path length on
    # the system, we should pick a conservative default
    SPACK_SYS_MAX_PATH_LENGTH = 1024

padding_regex = re.compile(r'(\$[\w\d\:]+\b|\$\{[\w\d\:]+\})')


def substitute_config_variables(path):
    """Substitute placeholders into paths.

    Spack allows paths in configs to have some placeholders, as follows:

    - $spack     The Spack instance's prefix
    - $user      The current user's username
    - $tempdir   Default temporary directory returned by tempfile.gettempdir()

    These are substituted case-insensitively into the path, and users can
    use either ``$var`` or ``${var}`` syntax for the variables.

    """
    # Look up replacements for re.sub in the replacements dict.
    def repl(match):
        m = match.group(0).strip('${}')
        return replacements.get(m.lower(), match.group(0))

    # Replace $var or ${var}.
    return re.sub(r'(\$\w+\b|\$\{\w+\})', repl, path)


def substitute_path_variables(path):
    """Substitute config vars, expand environment vars, expand user home."""
    path = substitute_config_variables(path)
    path = os.path.expandvars(path)
    path = os.path.expanduser(path)
    return path


def _get_padding_string(length):
    num_reps = int(length / (SPACK_PATH_PADDING_SIZE + 1))
    extra_chars = length % (SPACK_PATH_PADDING_SIZE + 1)
    reps_list = [SPACK_PATH_PADDING_CHARS for i in range(num_reps)]
    reps_list.append(SPACK_PATH_PADDING_CHARS[:extra_chars])
    return os.path.sep.join(reps_list)


def _add_computed_padding(path):
    """Subtitute in padding of os-specific length.  The intent is to leave
    SPACK_MAX_INSTALL_PATH_LENGTH characters available for parts of the
    path generated by spack.  This is to allow for not-completely-known
    lengths of things like os/arch, compiler, package name, hash length,
    etc.
    """
    m = padding_regex.search(path)
    if m and m.group(0).strip('${}').startswith('padding'):
        padding_part = m.group(0)
        len_pad_part = len(m.group(0))
        p_match = re.search(r'\:(\d+)', padding_part)
        if p_match:
            computed_padding = _get_padding_string(int(p_match.group(1)))
        else:
            # Take whatever has been computed/substituted so far and add some
            # room
            path_len = len(path) - len_pad_part + SPACK_MAX_INSTALL_PATH_LENGTH
            needed_pad_len = SPACK_SYS_MAX_PATH_LENGTH - path_len
            computed_padding = _get_padding_string(needed_pad_len)
        return padding_regex.sub(computed_padding, path)
    return path


def canonicalize_path(path):
    """Same as substitute_path_variables, but also take absolute path."""
    path = substitute_path_variables(path)
    path = os.path.abspath(path)
    path = _add_computed_padding(path)

    return path
