dealii 9.0.1 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache, jobs_scratch_dir]
    when: always
  dependencies: [trilinos 12.14.0-rc1 gcc@5.5.0 linux-centos7-x86_64, nanoflann 1.2.3
      gcc@5.5.0 linux-centos7-x86_64, adol-c develop gcc@5.5.0 linux-centos7-x86_64,
    intel-tbb 2019 gcc@5.5.0 linux-centos7-x86_64, openmpi 3.1.2 gcc@5.5.0 linux-centos7-x86_64,
    oce 0.18.3 gcc@5.5.0 linux-centos7-x86_64, arpack-ng 3.6.3 gcc@5.5.0 linux-centos7-x86_64,
    netlib-scalapack 2.0.2 gcc@5.5.0 linux-centos7-x86_64, gsl 2.5 gcc@5.5.0 linux-centos7-x86_64,
    suite-sparse 5.3.0 gcc@5.5.0 linux-centos7-x86_64, petsc 3.10.2 gcc@5.5.0 linux-centos7-x86_64,
    sundials 3.2.1 gcc@5.5.0 linux-centos7-x86_64, muparser 2.2.5 gcc@5.5.0 linux-centos7-x86_64,
    boost 1.68.0 gcc@5.5.0 linux-centos7-x86_64, metis 5.1.0 gcc@5.5.0 linux-centos7-x86_64,
    p4est 2.0 gcc@5.5.0 linux-centos7-x86_64, openblas 0.3.3 gcc@5.5.0 linux-centos7-x86_64,
    cmake 3.12.3 gcc@5.5.0 linux-centos7-x86_64, zlib 1.2.11 gcc@5.5.0 linux-centos7-x86_64,
    hdf5 1.10.4 gcc@5.5.0 linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-14
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: trilinos 12.14.0-rc1
      gcc@5.5.0 linux-centos7-x86_64;nanoflann 1.2.3 gcc@5.5.0 linux-centos7-x86_64;adol-c
      develop gcc@5.5.0 linux-centos7-x86_64;intel-tbb 2019 gcc@5.5.0 linux-centos7-x86_64;openmpi
      3.1.2 gcc@5.5.0 linux-centos7-x86_64;oce 0.18.3 gcc@5.5.0 linux-centos7-x86_64;arpack-ng
      3.6.3 gcc@5.5.0 linux-centos7-x86_64;netlib-scalapack 2.0.2 gcc@5.5.0 linux-centos7-x86_64;gsl
      2.5 gcc@5.5.0 linux-centos7-x86_64;suite-sparse 5.3.0 gcc@5.5.0 linux-centos7-x86_64;petsc
      3.10.2 gcc@5.5.0 linux-centos7-x86_64;sundials 3.2.1 gcc@5.5.0 linux-centos7-x86_64;muparser
      2.2.5 gcc@5.5.0 linux-centos7-x86_64;boost 1.68.0 gcc@5.5.0 linux-centos7-x86_64;metis
      5.1.0 gcc@5.5.0 linux-centos7-x86_64;p4est 2.0 gcc@5.5.0 linux-centos7-x86_64;openblas
      0.3.3 gcc@5.5.0 linux-centos7-x86_64;cmake 3.12.3 gcc@5.5.0 linux-centos7-x86_64;zlib
      1.2.11 gcc@5.5.0 linux-centos7-x86_64;hdf5 1.10.4 gcc@5.5.0 linux-centos7-x86_64,
    HASH: qdzzhxa2wumf5gjqwiyzjbjwll4e2r3n, MIRROR_URL: 'https://mirror.spack.io',
    ROOT_SPEC: xsdk@0.4.0%gcc@5.5.0}

dealii 9.0.1 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache, jobs_scratch_dir]
    when: always
  dependencies: [trilinos 12.14.0-rc1 gcc@5.5.0 linux-ubuntu18.04-x86_64, nanoflann
      1.2.3 gcc@5.5.0 linux-ubuntu18.04-x86_64, adol-c develop gcc@5.5.0 linux-ubuntu18.04-x86_64,
    intel-tbb 2019 gcc@5.5.0 linux-ubuntu18.04-x86_64, openmpi 3.1.2 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    oce 0.18.3 gcc@5.5.0 linux-ubuntu18.04-x86_64, arpack-ng 3.6.3 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    netlib-scalapack 2.0.2 gcc@5.5.0 linux-ubuntu18.04-x86_64, gsl 2.5 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    suite-sparse 5.3.0 gcc@5.5.0 linux-ubuntu18.04-x86_64, petsc 3.10.2 gcc@5.5.0
      linux-ubuntu18.04-x86_64, sundials 3.2.1 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    muparser 2.2.5 gcc@5.5.0 linux-ubuntu18.04-x86_64, boost 1.68.0 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    metis 5.1.0 gcc@5.5.0 linux-ubuntu18.04-x86_64, p4est 2.0 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    openblas 0.3.3 gcc@5.5.0 linux-ubuntu18.04-x86_64, cmake 3.12.3 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    zlib 1.2.11 gcc@5.5.0 linux-ubuntu18.04-x86_64, hdf5 1.10.4 gcc@5.5.0 linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-14
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: trilinos 12.14.0-rc1
      gcc@5.5.0 linux-ubuntu18.04-x86_64;nanoflann 1.2.3 gcc@5.5.0 linux-ubuntu18.04-x86_64;adol-c
      develop gcc@5.5.0 linux-ubuntu18.04-x86_64;intel-tbb 2019 gcc@5.5.0 linux-ubuntu18.04-x86_64;openmpi
      3.1.2 gcc@5.5.0 linux-ubuntu18.04-x86_64;oce 0.18.3 gcc@5.5.0 linux-ubuntu18.04-x86_64;arpack-ng
      3.6.3 gcc@5.5.0 linux-ubuntu18.04-x86_64;netlib-scalapack 2.0.2 gcc@5.5.0 linux-ubuntu18.04-x86_64;gsl
      2.5 gcc@5.5.0 linux-ubuntu18.04-x86_64;suite-sparse 5.3.0 gcc@5.5.0 linux-ubuntu18.04-x86_64;petsc
      3.10.2 gcc@5.5.0 linux-ubuntu18.04-x86_64;sundials 3.2.1 gcc@5.5.0 linux-ubuntu18.04-x86_64;muparser
      2.2.5 gcc@5.5.0 linux-ubuntu18.04-x86_64;boost 1.68.0 gcc@5.5.0 linux-ubuntu18.04-x86_64;metis
      5.1.0 gcc@5.5.0 linux-ubuntu18.04-x86_64;p4est 2.0 gcc@5.5.0 linux-ubuntu18.04-x86_64;openblas
      0.3.3 gcc@5.5.0 linux-ubuntu18.04-x86_64;cmake 3.12.3 gcc@5.5.0 linux-ubuntu18.04-x86_64;zlib
      1.2.11 gcc@5.5.0 linux-ubuntu18.04-x86_64;hdf5 1.10.4 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    HASH: qdzzhxa2wumf5gjqwiyzjbjwll4e2r3n, MIRROR_URL: 'https://mirror.spack.io',
    ROOT_SPEC: xsdk@0.4.0%gcc@5.5.0}
